=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/validation/all/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test" targetNamespace="test">

  <complexType name="all">
    <all minOccurs="1">
      <element name="a" type="string"/>
      <element name="b" type="string"/>
      <element name="c" type="string" minOccurs="0"/>
    </all>
  </complexType>

  <complexType name="type">
    <sequence>
      <element name="all" type="t:all" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/validation/all/test-000.xml
<t:root xmlns:t="test"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <!-- all combinations -->
  <all>
    <a>a</a>
    <b>b</b>
    <c>c</c>
  </all>

  <all>
    <a>a</a>
    <c>c</c>
    <b>b</b>
  </all>

  <all>
    <b>b</b>
    <a>a</a>
    <c>c</c>
  </all>

  <all>
    <b>b</b>
    <c>c</c>
    <a>a</a>
  </all>

  <all>
    <c>c</c>
    <a>a</a>
    <b>b</b>
  </all>

  <all>
    <c>c</c>
    <b>b</b>
    <a>a</a>
  </all>

  <!-- optional c is not present -->
  <all>
    <a>a</a>
    <b>b</b>
  </all>

  <all>
    <a>a</a>
    <b>b</b>
  </all>

</t:root>

=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/validation/restriction/test-003.xml
<t:root xmlns:t="test"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <!-- valid base but not restriction: sequence maxOccurs="1" -->
  <restriction-a z="z">
    <a>a</a>
    <b>b</b>
    <c>c</c>

    <a>a</a>
    <b>b</b>
    <c>c</c>
  </restriction-a>

</t:root>
