=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/examples/cxx/serializer/minimal/people.xsd
<?xml version="1.0"?>

<!--

file      : examples/cxx/serializer/minimal/people.xsd
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : not copyrighted - public domain

-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:simpleType name="gender">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="male"/>
      <xsd:enumeration value="female"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="person">
    <xsd:sequence>
      <xsd:element name="first-name" type="xsd:string"/>
      <xsd:element name="last-name" type="xsd:string"/>
      <xsd:element name="gender" type="gender"/>
      <xsd:element name="age" type="xsd:unsignedShort"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="people">
    <xsd:sequence>
      <xsd:element name="person" type="person" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="people" type="people"/>

</xsd:schema>

=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/examples/cxx/hybrid/filter/people.xml
<?xml version="1.0"?>

<!--

file      : examples/cxx/hybrid/filter/people.xml
author    : Boris Kolpackov <boris@codesynthesis.com>
copyright : not copyrighted - public domain

-->

<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="people.xsd">

  <person>
    <first-name>John</first-name>
    <last-name>Doe</last-name>
    <gender>male</gender>
    <age>32</age>
  </person>

  <person>
    <first-name>Jane</first-name>
    <last-name>Doe</last-name>
    <gender>female</gender>
    <age>28</age>
  </person>

  <person>
    <first-name>Joe</first-name>
    <last-name>Dirt</last-name>
    <gender>male</gender>
    <age>25</age>
  </person>

</people>
