=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/validation/choice/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test" targetNamespace="test">

  <complexType name="choice">
    <choice maxOccurs="3">
      <element name="a" type="string"/>
      <element name="b" type="string" maxOccurs="unbounded"/>
      <sequence>
        <element name="c" type="string" minOccurs="0"/>
	<element name="d" type="string"/>
      </sequence>
      <any namespace="other" maxOccurs="unbounded"/>
    </choice>
  </complexType>

  <complexType name="type">
    <sequence>
      <element name="choice" type="t:choice" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/validation/choice/test-000.xml
<t:root xmlns:t="test"
        xmlns:o="other"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <choice>
    <a>a</a>

    <b>b</b>
  </choice>

  <choice>
    <c>c</c>
    <d>d</d>

    <o:any>any</o:any>

    <a>a</a>
  </choice>

  <choice>
    <c>c</c>
    <d>d</d>

    <d>d</d>

    <a>a</a>
  </choice>

</t:root>
