=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/polymorphism/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test" targetNamespace="test">

  <complexType name="base">
    <sequence>
      <element name="a" type="int"/>
    </sequence>
  </complexType>

  <element name="base" type="t:base"/>
  <element name="another-base" type="t:base" substitutionGroup="t:base"/>

  <complexType name="interm">
    <complexContent>
      <extension base="t:base">
        <sequence>
          <element name="b" type="int"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <element name="interm" type="t:interm" substitutionGroup="t:base"/>

  <complexType name="derived">
    <complexContent>
      <extension base="t:interm">
        <sequence>
          <element name="c" type="int"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <element name="derived" type="t:derived" substitutionGroup="t:interm"/>

  <complexType name="type">
    <sequence>
      <element ref="t:base" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/polymorphism/test-000.xml
<t:root xmlns:t="test"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <t:base><a>1</a></t:base>

  <t:base xsi:type="t:interm"><a>1</a><b>2</b></t:base>
  <t:interm><a>1</a><b>2</b></t:interm>

  <t:base xsi:type="t:derived"><a>1</a><b>2</b><c>3</c></t:base>
  <t:derived><a>1</a><b>2</b><c>3</c></t:derived>

  <!-- same type substitution -->

  <t:another-base><a>1</a></t:another-base>
  <t:base xsi:type="t:base"><a>1</a></t:base>
  <t:another-base xsi:type="t:base"><a>1</a></t:another-base>

</t:root>
