=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/recursive/test.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- test 1 -->

  <xs:complexType name="sub_type">
    <xs:sequence>
      <xs:element name="sub" type="sub_type" minOccurs="0"/>
      <xs:element name="indir" type="indir_type" minOccurs="0"/>
      <xs:element name="sub2" type="sub_type" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="indir_type">
    <xs:sequence>
      <xs:element name="sub" type="sub_type" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>

  <!-- test 2 -->

  <xs:element name="a">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="a" />
          <xs:element ref="b" />
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="b">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <!-- root -->

  <xs:complexType name="test_type">
    <xs:choice>
      <xs:element name="sub" type="sub_type" />
      <xs:element ref="a"/>
    </xs:choice>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>

  <xs:element name="test" type="test_type" />
</xs:schema>

=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/recursive/test-001.xml
<test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="test.xsd"
      name="testName">
<a name="1">
    <b name="b1"/>
<a name="2">
    <b name="b1"/>
<a name="3">
    <b name="b3"/>
<a name="4">
    <b name="b4"/>
<a name="5">
    <b name="b5"/>
<a name="6">
    <b name="b6"/>
<a name="7">
    <b name="b7"/>
<a name="8">
    <b name="b8"/>
<a name="9">
    <b name="b9"/>
<a name="10">
    <b name="b10"/>
<a name="11">
    <b name="b11"/>
<a name="12">
    <b name="b12"/>
<a name="13">
    <b name="b13"/>
<a name="14">
    <b name="b14"/>
<a name="15">
    <b name="b15"/>

</a>
</a>
</a>
</a>
</a>
</a>
</a>
</a>
</a>
</a>
</a>
</a>
</a>
</a>
</a>
</test>
