=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/validation/sequence/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test" targetNamespace="test">

  <complexType name="sequence">
    <sequence minOccurs="1" maxOccurs="2">
      <element name="a" type="string" minOccurs="0"/>
      <sequence>
        <element name="b" type="string" minOccurs="0"/>
        <element name="c" type="string"/>
      </sequence>
      <element name="d" type="string" maxOccurs="unbounded"/>
      <sequence>
        <any namespace="##targetNamespace other"/>
	<element name="f" type="string"/>
      </sequence>
      <element name="e" type="string" maxOccurs="2"/>
    </sequence>
  </complexType>

  <complexType name="type">
    <sequence>
      <element name="sequence" type="t:sequence" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/validation/sequence/test-006.xml
<t:root xmlns:t="test"
        xmlns:o="other"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <!-- fail e maxOccurs="2" -->
  <sequence>
    <c>c</c>
    <d>d</d>
    <t:any>any</t:any>
    <f>f</f>
    <e>e</e>
    <e>e</e>
    <e>e</e>
  </sequence>

</t:root>

=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/validation/sequence/test-003.xml
<t:root xmlns:t="test"
        xmlns:o="other"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <!-- fail a maxOccurs="1" -->
  <sequence>
    <a>a</a>
    <a>a</a>
    <c>c</c>
    <d>d</d>
    <t:any>any</t:any>
    <f>f</f>
    <e>e</e>
  </sequence>

</t:root>
