=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/built-in/test.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:t="test" targetNamespace="test">

  <complexType name="type">
    <sequence>
      <element name="any-type" type="anyType" maxOccurs="unbounded"/>
      <element name="any-simple-type" type="anySimpleType" maxOccurs="unbounded"/>

      <element name="boolean" type="boolean" maxOccurs="unbounded"/>

      <element name="byte" type="byte" maxOccurs="unbounded"/>
      <element name="unsigned-byte" type="unsignedByte" maxOccurs="unbounded"/>
      <element name="short" type="short" maxOccurs="unbounded"/>
      <element name="unsigned-short" type="unsignedShort" maxOccurs="unbounded"/>
      <element name="int" type="int" maxOccurs="unbounded"/>
      <element name="unsigned-int" type="unsignedInt" maxOccurs="unbounded"/>
      <element name="long" type="long" maxOccurs="unbounded"/>
      <element name="unsigned-long" type="unsignedLong" maxOccurs="unbounded"/>

      <element name="integer" type="integer" maxOccurs="unbounded"/>
      <element name="negative-integer" type="negativeInteger" maxOccurs="unbounded"/>
      <element name="non-positive-integer" type="nonPositiveInteger" maxOccurs="unbounded"/>
      <element name="positive-integer" type="positiveInteger" maxOccurs="unbounded"/>
      <element name="non-negative-integer" type="nonNegativeInteger" maxOccurs="unbounded"/>

      <element name="float" type="float" maxOccurs="unbounded"/>
      <element name="double" type="double" maxOccurs="unbounded"/>
      <element name="decimal" type="decimal" maxOccurs="unbounded"/>

      <element name="string" type="string" maxOccurs="unbounded"/>
      <element name="normalized-string" type="normalizedString" maxOccurs="unbounded"/>
      <element name="token" type="token" maxOccurs="unbounded"/>
      <element name="name" type="Name" maxOccurs="unbounded"/>
      <element name="nmtoken" type="NMTOKEN" maxOccurs="unbounded"/>
      <element name="nmtokens" type="NMTOKENS" maxOccurs="unbounded"/>
      <element name="ncname" type="NCName" maxOccurs="unbounded"/>
      <element name="id" type="ID" maxOccurs="unbounded"/>
      <element name="idref" type="IDREF" maxOccurs="unbounded"/>
      <element name="idrefs" type="IDREFS" maxOccurs="unbounded"/>

      <element name="language" type="language" maxOccurs="unbounded"/>
      <element name="uri" type="anyURI" maxOccurs="unbounded"/>
      <element name="qname" type="QName" maxOccurs="unbounded"/>

      <element name="base64_binary" type="base64Binary" maxOccurs="unbounded"/>
      <element name="hex_binary" type="hexBinary" maxOccurs="unbounded"/>

      <element name="gday" type="gDay" maxOccurs="unbounded"/>
      <element name="gmonth" type="gMonth" maxOccurs="unbounded"/>
      <element name="gyear" type="gYear" maxOccurs="unbounded"/>
      <element name="gmonth_day" type="gMonthDay" maxOccurs="unbounded"/>
      <element name="gyear_month" type="gYearMonth" maxOccurs="unbounded"/>
      <element name="date" type="date" maxOccurs="unbounded"/>
      <element name="time" type="time" maxOccurs="unbounded"/>
      <element name="date_time" type="dateTime" maxOccurs="unbounded"/>
      <element name="duration" type="duration" maxOccurs="unbounded"/>

    </sequence>
  </complexType>

  <element name="root" type="t:type"/>

</schema>

=== HYDROXY-RESEARCH-GROUP/H20-DECOMPOSITION/tools/windows/xsde-3.2.0-i686-windows/tests/cxx/parser/built-in/test-001.xml
<t:root xmlns:t="test"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="test test.xsd">

  <any-type x="x">
    <a>a</a>
    <any-type x="xxx">aaa<a>bbb</a>ccc</any-type>
  </any-type>

  <any-simple-type>123abc</any-simple-type>

  <boolean>1</boolean>
  <boolean> 0 </boolean>
  <boolean>true</boolean>
  <boolean> false </boolean>

  <byte>0</byte>
  <byte>+127</byte>
  <byte>-128</byte>
  <byte> 123 </byte>

  <unsigned-byte>0</unsigned-byte>
  <unsigned-byte>255</unsigned-byte>
  <unsigned-byte> 123 </unsigned-byte>

  <short>0</short>
  <short>+32767</short>
  <short>-32768</short>
  <short> -12345 </short>

  <unsigned-short>0</unsigned-short>
  <unsigned-short>65535</unsigned-short>
  <unsigned-short> 12345 </unsigned-short>

  <int>0</int>
  <int>+2147483647</int>
  <int>-2147483648</int>
  <int> -1234567890 </int>

  <unsigned-int>0</unsigned-int>
  <unsigned-int>4294967295</unsigned-int>
  <unsigned-int> 1234567890 </unsigned-int>

  <long>0</long>
  <long>+9223372036854775807</long>
  <long>-9223372036854775808</long>
  <long> -1234567890123456789 </long>

  <unsigned-long>0</unsigned-long>
  <unsigned-long>18446744073709551615</unsigned-long>
  <unsigned-long> 12345678901234567890 </unsigned-long>

  <integer>0</integer>
  <integer> +2147483647 </integer>
  <integer>-02147483648</integer>
  <integer>-1234567890</integer>

  <negative-integer>-02147483648</negative-integer>
  <negative-integer> -1234567890 </negative-integer>

  <non-positive-integer>0</non-positive-integer>
  <non-positive-integer>-02147483648</non-positive-integer>
  <non-positive-integer> -1234567890 </non-positive-integer>

  <positive-integer>4294967295</positive-integer>
  <positive-integer> +01234567890 </positive-integer>

  <non-negative-integer>0</non-negative-integer>
  <non-negative-integer>4294967295</non-negative-integer>
  <non-negative-integer> +01234567890 </non-negative-integer>

  <float>0</float>
  <float>+0</float>
  <float>-0</float>
  <float>INF</float>
  <float>-INF</float>
  <float>NaN</float>
  <float> 123.567 </float>
  <float>+123.567</float>
  <float>-123.567e5</float>
  <float>-.45E-5</float>

  <double>0</double>
  <double>+0</double>
  <double>-0</double>
  <double>INF</double>
  <double>-INF</double>
  <double>NaN</double>
  <double> 123.567 </double>
  <double>+123.567</double>
  <double>-123.567e5</double>
  <double>-.45E-5</double>

  <decimal>0</decimal>
  <decimal>+0</decimal>
  <decimal>-0</decimal>
  <decimal> 123.567 </decimal>
  <decimal>+123.567</decimal>
  <decimal>-123.567</decimal>

  <string>string space
newline
  </string>

  <normalized-string> string space
newline

  </normalized-string>

  <token> string space
newline

  </token>

  <name> as123:345-.abs </name>

  <nmtoken> 1as123:345-.abs </nmtoken>

  <nmtokens> abc   123 </nmtokens>

  <ncname> as123_345-.abs </ncname>

  <id> as123_345-.abs </id>
  <id> abc </id>
  <id> a123 </id>

  <idref> as123_345-.abs </idref>

  <idrefs> abc   a123 </idrefs>

  <language> x </language>
  <language> en </language>
  <language> en-us </language>
  <language>one-two-three-four44-seven77-eight888</language>

  <uri>   </uri>
  <uri> relative </uri>
  <uri> #id </uri>
  <uri> http://www.example.com/foo#bar </uri>

  <qname>schemaLocation</qname>
  <qname>xsi:schemaLocation</qname>

  <base64_binary> MTIzND
                  VhYmNqaw = =</base64_binary>
  <base64_binary>YQ==</base64_binary>
  <base64_binary>YWI=</base64_binary>
  <base64_binary>YWJj</base64_binary>

  <hex_binary>  </hex_binary>
  <hex_binary> 31323334356162636a6b   </hex_binary>

  <gday>  ---12+12:00  </gday>
  <gday>---01</gday>
  <gday>---31</gday>
  <gday>---15Z</gday>
  <gday>---15-14:00</gday>

  <gmonth>  --10+12:00  </gmonth>
  <gmonth>--01</gmonth>
  <gmonth>--12Z</gmonth>

  <gyear>  2007+12:00  </gyear>
  <gyear>0001</gyear>
  <gyear>-20000Z</gyear>

  <gmonth_day>  --10-28+12:00  </gmonth_day>
  <gmonth_day>--12-31</gmonth_day>
  <gmonth_day>--01-01Z</gmonth_day>

  <gyear_month>  2007-12+12:00  </gyear_month>
  <gyear_month>-2007-10</gyear_month>
  <gyear_month>20007-10Z</gyear_month>
  <gyear_month>-20007-01</gyear_month>

  <date>  2007-12-26+12:00  </date>
  <date>-2007-10-15</date>
  <date>20007-12-31Z</date>
  <date>-20007-01-01</date>

  <time>  12:46:23.456+12:00  </time>
  <time>12:13:14</time>
  <time>12:13:14Z</time>

  <date_time>  2007-12-26T12:13:14.123+12:00  </date_time>
  <date_time>-2007-10-15T12:13:14</date_time>
  <date_time>20007-12-31T12:13:14Z</date_time>
  <date_time>-20007-01-01T12:13:14</date_time>

  <duration>  -P2007Y13M32DT25H61M61.123S  </duration>
  <duration>P1Y</duration>
  <duration>P1M</duration>
  <duration>P1D</duration>
  <duration>PT1H</duration>
  <duration>PT1M</duration>
  <duration>PT1.1S</duration>
  <duration>P1YT1S</duration>

</t:root>
